// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c6c43217-bc83-4129-90f8-17071a873a7c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PSlRc9dPQ",
    "aws_user_pools_web_client_id": "1docdb0qgn48ejpa2hg1iceptc",
    "oauth": {},
    "aws_user_files_s3_bucket": "seniorcare-local",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
